nodeLinker: node-modules

packageExtensions:
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  "@nuxtjs/eslint-config-typescript@*":
    peerDependencies:
      eslint: "*"
      webpack: "*"
  fork-ts-checker-webpack-plugin@*:
    peerDependencies:
      "@": "*"
<<<<<<< HEAD
      
yarnPath: .yarn/releases/yarn-2.4.2.cjs
=======

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
>>>>>>> cd64ac29f7c26aab54d81c026d75ab80a14272d1
