nodeLinker: node-modules

packageExtensions:
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  "@nuxtjs/eslint-config-typescript@*":
    peerDependencies:
      eslint: "*"
      webpack: "*"
  fork-ts-checker-webpack-plugin@*:
    peerDependencies:
      "@": "*"

yarnPath: ".yarn/releases/yarn-berry.cjs"