nodeLinker: node-modules

packageExtensions:
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  "@nuxtjs/eslint-config-typescript@*":
    peerDependencies:
      eslint: "*"
      webpack: "*"
  "@nuxtjs/eslint-module@*":
    peerDependencies:
      webpack: "*"
  fork-ts-checker-webpack-plugin@*:
    peerDependencies:
      "@": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-rc.js
