# This workflow will do a clean installation of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Semantic Release"
"on":
  push:
    branches: [ master, main ]
  workflow_dispatch:
jobs:
  build_and_release:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }} && {{ !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # Whether to configure the token or SSH key with the local git config
          # Default: true
          persist-credentials: false # <--- checking this in commit context

      - name: "Prepare: apply cache"
        uses: c-hive/gha-yarn-cache@v2  # using cache

      - name: "Setting up node & yarn"
        uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: lts/*
          cache-dependency-path: |
            **/package-lock.json
            **/yarn.lock
          architecture: "x64" # optional, x64 or x86. If not specified, x64 will be used by default

      - name: "Prepare: yarn@3 & firebase-tools setup"
        run: yarn set version 3.1.1 && yarn install

      - name: "Semantic release processing"
        run: npx semantic-release
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
